#ci-cd-pipeline.yml
@
name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Étape pour installer Docker
      - name: Install Docker
        uses: docker/setup-docker@v2
        with:
          docker-version: '20.10.7'
          
      # Étape pour construire et tester l'application Python
      - name: Build and test Python app
        run: |
          cd app_python
          docker build -t mon_image .
          docker run mon_image python -m unittest discover tests

      # Étape pour déployer l'application dans un conteneur Docker
      - name: Deploy app to Docker container
        run: |
          docker run -d -p 5000:5000 mon_image

